### ISSUE TITLE
Can you clarify what this extension does?

### ISSUE THREAD

**Issue by ovizii** [Magisk-Modules-Repo/App-Data-Keeper#1]
From the sound of it it is supposed to make APKs and app data survive a wipe. Yet, later I read this sentence in your description:

> Besides app data being already in place, adk uses rsync to backup APK's. 

What do you mean by app data is already in place? Where would it come from after a factory reset?

**Comment by VR-25** [comment]
The standard TWRP factory reset doesn't wipe /data/media. This module stores app data at /data/media/adk/.appData. So...

**Comment by ovizii** [comment]
still confused. I understand that stuff inside /data/media survives a factory reset. 
Does your extensions redirect apks or app data to  /data/media/adk/.appData ? 

Doesn't a factory reset wipe app data? Then how can app data already be in place? 

I did google, trying to udnerstand this and foudn out:

> All apps (root or not) have a default data directory, which is /data/data/<package_name>. By default, the apps databases, settings, and all other data go here. 
Does this mean your extensions backs up apks and app data or only one of them (which?) 

Sorry for all the questions I am honestly just trying to wrap my head around this.

**Comment by ovizii** [comment]
I'm closing this as you have replied in the XDA thread and clarified all the questions:

> This module redirects user and updated system apps data (yes, data only) from /data/data to /data/media/adk/.appData, which is not affected by TWRP's standard factory reset. In addition, it copies (doesn't move) the respective APK's to $sdcard/adk/apksBkp or to /data/media/adk/apksBkp if no sdcard is found.
